name: Release CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"
          registry-url: https://npm.pkg.github.com/
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build lib
        run: npm run build
      - name: Cypress run
        run: npm run test:e2e
      - name: Release
        working-directory: lib
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
