name: Release CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"
          registry-url: https://npm.pkg.github.com/
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build lib
        run: npm run build
      - name: Release GH
        working-directory: lib
        run: npx publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Setup Node for npm
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Build lib
        run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          token: ${{ secrets.NPM_TOKEN }}
